### ISSUE TITLE
Simpleserver 1.6.4 Map loading issue

### ISSUE THREAD

**Issue by PTY997** [SimpleServer/SimpleServer#29] opened 2011-05-27 03:39 UTC
Hi i recently updated and got it all workign but when i connect i seem to be floating in blue air and only a few blocks are spawning, the map doesn't seem to want to load any help?

**Comment by vorpalhex** [comment] 2011-05-27 04:03
I've had this issue, but it does not seem to be a SimpleServer issue.  Unfortunately I am not 100% certain as to the cause.  Can you confirm by running minecraft_server.jar directly instead of using SimpleServer, to see if the issue persists?

**Comment by PTY997** [comment] 2011-05-27 09:40
Yes if i use the MC.jar file the the problem goes.

Update:

When I sit on the SSserver waiting for it to load I get the internal error read timed out

**Comment by dola** [comment] 2011-05-27 18:53
according to this tweet (http://fwd4.me/02T4) from notch, those problems are not in SimpleServer but in the vanilla server. So there might be an update tomorrow on the vanilla to fix this.

**Comment by vorpalhex** [comment] 2011-05-27 18:54
I'm closing this for now. If the update doesn't fix it in this case, we can re-open the issue.

**Closed as completed by vorpalhex** 2011-05-27 18:54 UTC
Labels: Bug Report

**Comment by PTY997** [comment] 2011-05-27 19:02
ok but this only happens when i use the SimpleServer since i updated it it worked fine for 1.5

**Comment by heapoutofspace** [comment] 2011-05-27 20:33
See Notch's [tweet](https://twitter.com/#!/notch/status/74182283631923200)
