### ISSUE TITLE
Stuck on login with 1.1 update

### ISSUE THREAD

**Issue by ricrick** [SimpleServer/SimpleServer#220] opened 2012-01-12 21:37 UTC
as title.

**Comment by kevinpeno** [comment] 2012-01-12 23:04
Confirmed.

**Comment by bryanburke** [comment] 2012-01-13 06:04
Changes in protocol from 1.0.1 to 1.1: http://wiki.vg/Protocol#2012-01-12

If everyone else is busy (like me), I will try to update the StreamTunnel and Bot as soon as I can.

**Comment by kevinpeno** [comment] 2012-01-13 06:51
@bryanburke Thanks for the reply. I found this today and wanted to help with a patch. However, and I apologize for my lack of understanding ahead of time, I'm not sure how to actually write a string into the stream. I see `readUTF16`, but is there a `writeUTF16`? If I understand correctly, this is what I would need in order to handle at least the login change.

**Comment by bryanburke** [comment] 2012-01-13 07:34
Fixed. See Issue #221 for Pull Request

@kevinpeno You can see my diff with the updates here: bryanburke/SimpleServer@35b797f656b84523bf9698067473ded21947bbd6

Basically, you need to do it this way:

``` java
write(readUTF16());
```

**Comment by kevinpeno** [comment] 2012-01-13 07:38
@bryanburke It looks like I was on the right track for everything. I just had one of them out of order and was confusing myself.  Thanks again for the reply and thanks for something to compare to. It helps me in understanding other people's code.

**Comment by bryanburke** [comment] 2012-01-13 07:48
No problem. It took me a while to get everything right as well. When I tested the new protocol with a local server and it worked, I couldn't believe I hadn't broken something. Lol

**Comment by kevinpeno** [comment] 2012-01-13 08:00
@bryanburke I can get in, but I can't seem to teleport (via bot). Looks like bots are timing out on login still.

**Comment by bryanburke** [comment] 2012-01-13 08:38
@kevinpeno Thanks for bringing that to my attention. I just fixed it.

**Comment by bryanburke** [comment] 2012-01-13 08:55
Well, I thought I fixed it! Now I can't figure out why the bots are still timing out. I'm sure one of the maintainers knows exactly what's happening here.

**Comment by ravngr** [comment] 2012-01-13 09:04
Take a look at ce3236d013b28aee2dfcce19459ee033329d1daa I was working on the same thing earlier and had bots working. I am making the assumption that since bots don't care about the level seed, it's safe to always say the level is default. Ideally you should merge bryanburke's code with this to send it the actual terrain type (if it matters).

Also worth noting that bow enchantments also need to be added to the /enchant command for proper 1.1 support (see 112332bc1df339d5aa66978d95a66c05df4799b5).

Tried to clean up my fork, I'll try to get around to working out pull requests at some point ;)

**Comment by bryanburke** [comment] 2012-01-13 17:43
@ravngr Thank you for posting the fix. I've merged the solution into my pull request (Pull Request #221).

It's true that bots don't care about level seed and type, since they are inserted every time at particular coordinates by the wrapper.

As for your enchantment updates, I would urge you to make a Pull Request with those changes and also add yourself to the list of CONTRIBUTORS.

Also, can we create a tag for 8.3.5 (or some future stable version)? We can't stay in RC forever.

**Closed as completed** 2012-01-21 03:04 UTC
