### ISSUE TITLE
Protocol error

### ISSUE THREAD

**Issue by wassilij** [SimpleServer/SimpleServer#43] opened 2011-05-30 20:08 UTC
I and my players get sometimes a Protocol error oO
All have Minecraft 1.6.5 ..

And sometimes (often by some players) you can write in the chat only 2-3 messages, then you need to relogg again (and then is often the protocol error).

Sorry for bad english.

**Comment by mrlannigan** [comment] 2011-06-01 09:01
I have somewhat confirmed what wassilij is reporting.  The wrapper starts up just fine and launches the server jar, but when the client tries to connect it hangs at the Logging In message.  The socket is eventually dropped because of a time out.

```SimpleServer -- Copyright (C) 2011 SimpleServer authors (see CONTRIBUTORS)
This program is licensed under The MIT License.
See file LICENSE for details.

> > Starting SimpleServer 8.1.3-456cf01
> > 148 recipes
> > 16 achievements
> > 2011-06-01 04:56:34 [INFO] Starting minecraft server version Beta 1.6.6
> > 2011-06-01 04:56:34 [INFO] Loading properties
> > 2011-06-01 04:56:34 [INFO] Starting Minecraft server on 127.0.0.1:25566
> > 2011-06-01 04:56:34 [INFO] Preparing level "world"
> > 2011-06-01 04:56:34 [INFO] Preparing start region for level 0
> > 2011-06-01 04:56:35 [INFO] Preparing start region for level 1
> > 2011-06-01 04:56:35 [INFO] Preparing spawn area: 32%
> > 2011-06-01 04:56:36 [INFO] Done (1631467408ns)! For help, type "help" or "?"
> > [SimpleServer] Wrapper listening on 0.0.0.0:25565 (connect here)
> > [SimpleServer] Note: 0.0.0.0 means all IP addresses; you want this.
> > [SimpleServer] IP Connection from 193.273.424.123!
> > [SimpleServer] java.io.EOFException
> > [SimpleServer] PlayerStream error handling traffic for 193.273.424.123
> > [SimpleServer] Disconnecting 193.273.424.123 due to inactivity.
> > [SimpleServer] Socket Closed: 193.273.424.123
> > stop
> > [SimpleServer] Stopping Server...
> > java.net.SocketTimeoutException: Read timed out
> > 2011-06-01 04:57:18 [INFO] julian1828 [/127.0.0.1:1462] lost connection
> > 2011-06-01 04:57:18 [INFO] CONSOLE: Stopping the server..
> > 2011-06-01 04:57:18 [INFO] CONSOLE: Stopping the server..
> > 2011-06-01 04:57:18 [INFO] Stopping server
> > 2011-06-01 04:57:18 [INFO] Saving chunks
> > 2011-06-01 04:57:18 [INFO] Saving chunks
> > [SimpleServer] Server stopped successfully!
> > 
> > ```
> > ```
- I replaced my IP with a fake one.

**Comment by heapoutofspace** [comment] 2011-06-01 19:48
`java.io.EOFException` usually means the client disconnected unexpectedly. I can't reproduce it myself, so tell me what systems you're using.

**Comment by mrlannigan** [comment] 2011-06-03 09:55
I'm running the server in xp pro sp3.  I have found a work around, kinda.  When I start the server using the bat, it loads up.  I go to connect.  The game and server appear to hang.  I type something into server...just a random text string and press enter.  Seemingly that makes everything work.  The game loads up and everything works as expected until I stop/restart the server.  This happens everytime I start the server.  But once I log in once, I can log in and out multiple times with no problem.  If you want I can screen cast what I am seeing.  I also ran wireshark to see what was being communicated between the client and the server.  The client and the server make connection, pass the 01 and 02 packets and then hangs on the success response from the server after the login.

Just to clarify:
Client: Ubuntu linux 11.04
Server: windows xp pro sp3

I'm running the latest versions of all mc software.

**Comment by heapoutofspace** [comment] 2011-06-03 16:01
It seem like this is somehow connected to #44. Guess I have to set up a VM with XP to test it.

**Comment by JakeDiFebo** [comment] 2011-10-09 22:15
This is EXACTLY what drove many people insane before we switched to the 8.3.4, but now we only get it every once in awhile.

**Comment by acertain** [comment] 2011-10-10 03:38
i get this same problem(or something related) on a mac(cilent) and linux(server) with the launch.sh #149

**Comment by dola** [comment] 2011-11-28 10:32
outdated -> closing

**Closed as completed by dola** 2011-11-28 10:32 UTC
Labels: Bug Report
